### ISSUE TITLE
"ler"

### ISSUE THREAD

**Issue by Willem3141** [Willem3141/navi-reykunyu#1]
Lì'uri alu **ler**, plltxe Reykunyu san

> **Forms**
> <noun> (a)-ler  or  ler-a <noun>

Slä `<noun> ler` ke lu kangay, ha zene Reykunyu pivlltxe san `<noun> a-ler` sìk tup san `<noun> (a)-ler` sìk.

Kezemplltxe, tìngäzìk lu fwa tìtsyul lì'uä alu **ler** lu **le-**. Zeyko a fì'u latsu ep'ang nì'it.

**Comment by tirea** [comment]
Lì'uri alu `leyr` fìkxeyey len nìteng.

**Comment by Willem3141** [comment]
Irayo ma Tirea! Fpìl oel futa zeyko fìkxeyeyt a fya'o aswey lu fwa lì'kongit tiam. Txo ngiva' lì'ul 'awa lì'kongit nì'aw, tsakrr ke tsivun ngiva' lì'uvit alu **le-**, ha fko ke zene sivar lì'uvit alu **a-**. Txo ngiva' lì'ul melì'kongit (fu nì'ul), ulte lì'kong a'awve lu **le**, tsakrr ke lu tìkin a sar lì'uvit alu **a-**.

**Comment by tirea** [comment]
Sìltsana säfpìl 👍
