### ISSUE TITLE
Add popovers for the word type abbreviations

### ISSUE THREAD

**Issue by Willem3141** [Willem3141/navi-reykunyu#69]

**Comment by bew** [comment]
Thanks, I'm wondering how hard it would be to explain what each are, or maybe just put a mini example?

For example I don't really know what `intransitive verb` actually mean

**Comment by Willem3141** [comment]
I've added popovers now. I think having explanations is a good idea in principle, however I don't know if they really belong in a dictionary. A proper explanation of what "intransitive verb" means would need to be quite length and need a lot of context to be understood anyway... it may be better to just point people at a dedicated grammar guide if they need help with word types :thinking:
